# Generated by Django 2.1.9 on 2019-06-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srhapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
