# Generated by Django 2.1 on 2019-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srhapp', '0002_auto_20190620_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='title',
            field=models.CharField(max_length=255, verbose_name='商品名'),
        ),
    ]
